apiVersion: v1
kind: Service
metadata:
  name: gacha-engine-service
  namespace: gacha-engine-service
  labels:
    app.kubernetes.io/name: gacha-engine-service
    app.kubernetes.io/part-of: gacha-engine-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gacha-engine-service
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

